---
title: "Homework 1 for R language and data analysis"
author: "Qiang Shen"
date: "Dec.3,2017"
output:
  pdf_document: default
  word_document: default
---

**Use the knowledge learned from the course to solve the following questions.

1. Use R to Estimate what is the total area covered in blue of cos(x) function (from 1/2\*pi to 5/4\*pi and from 3/2\*pi to 2*pi). (1% deviation from the true value is acceptable. hint: in R $\pi$ is "pi".)

```{r,echo=F}
n=200
x<-seq(-10,10,length=n)
y<-cos(x)
plot(x,y,type='l',xlim=c(0,2.5*pi),main="cos(x)")

x<-seq(1/2*pi,5/4*pi,length=100)
y<-cos(x)
abline(h=0)
polygon(c(1/2*pi,x,5/4*pi),c(0,y,0),col="cornflowerblue")

x<-seq(3/2*pi,2*pi,length=100)
y<-cos(x)
abline(h=0)
polygon(c(3/2*pi,x,2*pi),c(0,y,0),col="cornflowerblue")
```

2. If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23.Find the sum of all the multiples of both 5 and 7 below 1000.(hint: summation function in R is *sum*.For example, **sum(1:4) equals 10**)

3. Install package *ggplot2* and then export the build-in dataset available in the package named *presidential* to files "presidential.csv"" and "presidential.txt". Once exported, then import files "presidential.csv" back to R accordingly.(Note for each variable in the imported data file,it should have the same type as the orginal dataset *presidential* and you can use the command *identical* to check whether the two datasets are the same or not, if it's identical, then *TRUE* will be returned. Hints: use **as.Date** to convert corresponding character into date).

4. In data file named "Restaurant.dta" attached:

      1>.  Find the row name/index of the observations with the missing value in variable named *mealprice*.

      2>.  to generate a data file without the observations with missing value in *mealprice* and exported it as *Restaurant_new.csv*.


5. In data file named "Grades.dta" attached:
  Generate a new variable called *group*  and classify those who have *gpa* equal or large than 3.5 as *excellent*, equal or large than 2 but smaller than 3.5 as *pass* and the rest as *fail* and then exported the a new data file called *Grades_new.csv*.




